spring.application.name=entity-module

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/entity-module
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# OpenAI
spring.ai.openai.api-key=ENTITY_MODULE_OPEN_AI_KEY
